<?php

define('CDEK_WEIGHT', 3000);
define('CDEK_FREE_PRICE', 5000);


define('SPECIAL_IBLOCK_ID', 62);

define('CATALOG_IBLOCK_ID', 4);
define('CATALOG_OFFERS_IBLOCK_ID', 5);
define('URL_1C', 'http://83.142.166.84/torgovlya/ws/Quantity?wsdl');

define('BANNERS_IBLOCK_ID', 6);
define('ARTICLES_IBLOCK_ID', 7);
define('COLORS_IBLOCK_ID', 10);
define('COMMENTS_IBLOCK_ID', 11);
define('SIZES_IBLOCK_ID', 13);
define('NEWS_IBLOCK_ID', 19);
define('ADVANTAGES_IBLOCK_ID', 54);

define('SMSLOG_HLBLOCK_ID', 1);

define('RUSSIANPOST_DELIVERY_ID', 7);

define('CATALOG_SECTION_NOPHOTO_FILE_ID', 965037); // TODO: change to real file id
define('CATALOG_SECTION_PICTURE_WIDTH', 220);
define('CATALOG_SECTION_PICTURE_HEIGHT', 276);
define('CATALOG_DETAIL_PICTURE_WIDTH', 300);
define('CATALOG_DETAIL_PICTURE_HEIGHT', 385);
// define('CATALOG_DETAIL_SMALL_PICTURE_WIDTH', 42);
// define('CATALOG_DETAIL_SMALL_PICTURE_HEIGHT', 52);
define('CATALOG_DETAIL_BIG_PICTURE_WIDTH', 1000);
define('CATALOG_DETAIL_BIG_PICTURE_HEIGHT', 800);
define('CATALOG_RECOMMENDED_PRODUCTS_PICTURE_WIDTH', 140);
define('CATALOG_RECOMMENDED_PRODUCTS_PICTURE_HEIGHT', 175);
define('CATALOG_VIEWED_PRODUCTS_PICTURE_WIDTH', 220);
define('CATALOG_VIEWED_PRODUCTS_PICTURE_HEIGHT', 276);
define('BASKET_PICTURE_WIDTH', 60);
define('BASKET_PICTURE_HEIGHT', 88);
define('CATALOG_SECTIONS_PICTURE_WIDTH', 298);
define('CATALOG_SECTIONS_PICTURE_HEIGHT', 438);

define('ACTION_ENABLED_ORDER_PROP_ID', 30);

define('CONTENT_MANAGERS_GROUP_ID', 11);